<div class="row column expanded">
	<h1>Welcome to <span class="zf-green">Zend Framework</span></h1>
</div>

<div class="row column expanded">
	<p>Congratulations! You have successfully installed the <a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">ZF Skeleton Application</a>. You are currently running Zend Framework version <?= \Application\Module::VERSION ?>. This skeleton can serve as a simple starting point for you to begin building your application on ZF.</p>
</div>
